/**
 * This class is generated by jOOQ
 */
package com.sivalabs.demo.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_CEEA1F35_2748_4F90_831E_AEA16D64A760</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_CEEA1F35_2748_4F90_831E_AEA16D64A760 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_CEEA1F35_2748_4F90_831E_AEA16D64A760", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
