/**
 * This class is generated by jOOQ
 */
package com.sivalabs.demo.jooq.domain;


import com.sivalabs.demo.jooq.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.USERS
	 */
	public static final Users USERS = com.sivalabs.demo.jooq.domain.tables.Users.USERS;
}
